# -*- coding: utf-8 -*-
"""ANLP_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdFd3IGOhXSyAm9bQAOEwjNkZUNinnnH

# **DOWNLOADING DATASET AND EDA**
"""

import os
import shutil
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datasets import load_dataset

# 1. Define the directory to be deleted
drive_path = "/content/drive/MyDrive/Medical_QA_Project"

# 3. Load the raw dataset
dataset_name = "MustafaIbrahim/medical-arabic-qa"
print(f"Loading raw dataset: {dataset_name}...")
dataset = load_dataset(dataset_name)

# 4. Convert the train split to a Pandas DataFrame for EDA
print("Converting to Pandas DataFrame...")
df = dataset['train'].to_pandas()

# 5. Exploratory Data Analysis (EDA)
print("\n--- Dataset Info ---")
df.info()

print("\n--- Missing Values ---")
print(df.isna().sum())

print("\n--- First 5 Rows ---")
display(df.head())

# 6. Feature Analysis: Calculate text lengths for questions and answers
cols = df.columns
if len(cols) >= 2:
    q_col = cols[0]
    a_col = cols[1]

    df['question_length'] = df[q_col].astype(str).apply(len)
    df['answer_length'] = df[a_col].astype(str).apply(len)

    # 7. Visualize the text length distributions
    plt.figure(figsize=(14, 5))

    plt.subplot(1, 2, 1)
    sns.histplot(df['question_length'], bins=50, color='blue', kde=True)
    plt.title('Question Length Distribution (Characters)')
    plt.xlabel('Length')
    plt.ylabel('Frequency')

    plt.subplot(1, 2, 2)
    sns.histplot(df['answer_length'], bins=50, color='green', kde=True)
    plt.title('Answer Length Distribution (Characters)')
    plt.xlabel('Length')
    plt.ylabel('Frequency')

    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure columns are defined
cols = df.columns
q_col = cols[0]
a_col = cols[1]

# 1. Word Count Analysis
print("Calculating word counts...")
df['question_word_count'] = df[q_col].astype(str).apply(lambda x: len(x.split()))
df['answer_word_count'] = df[a_col].astype(str).apply(lambda x: len(x.split()))

# 2. Visualize Word Count Distributions using Boxplots
plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
sns.boxplot(x=df['question_word_count'], color='orange')
plt.title('Question Word Count (Outliers Detection)')
plt.xlabel('Number of Words')

plt.subplot(1, 2, 2)
sns.boxplot(x=df['answer_word_count'], color='purple')
plt.title('Answer Word Count (Outliers Detection)')
plt.xlabel('Number of Words')

plt.tight_layout()
plt.show()

#3. Duplicates Analysis
print("\n--- Duplicates Analysis ---")
total_exact_duplicates = df.duplicated().sum()
duplicate_questions = df.duplicated(subset=[q_col]).sum()

print(f"Total exact duplicate rows: {total_exact_duplicates}")
print(f"Total duplicate questions (same question repeated): {duplicate_questions}")

# 4. Outliers Investigation (Extremely short texts)
print("\n--- Outliers Investigation ---")
min_answer_words = df['answer_word_count'].min()
print(f"The shortest answer has {min_answer_words} word(s).")

if min_answer_words < 3:
    print("\nExamples of extremely short answers:")
    display(df[df['answer_word_count'] <= 3][[q_col, a_col, 'answer_word_count']].head())

"""# Remove duplicate AND MISSING VALUES


"""

# Remove exact duplicate rows
initial_count = len(df)
df = df.drop_duplicates().reset_index(drop=True)
after_duplicates = len(df)

# Filter out rows with extremely short answers (less than 3 words)
# to ensure the model learns meaningful medical responses
df = df[df['answer_word_count'] >= 3].reset_index(drop=True)
final_count = len(df)

print(f"Initial row count: {initial_count}")
print(f"Count after removing duplicates: {after_duplicates}")
print(f"Final count after removing short answers: {final_count}")

"""#MAKE DATA VALID FOR FINE TUNING"""

from datasets import Dataset, DatasetDict

# Define the columns based on the dataset structure
# Assuming first column is Question and second is Answer
q_col = df.columns[0]
a_col = df.columns[1]

# Create a list of dictionaries in the ChatML format required by Qwen
formatted_data = []
for _, row in df.iterrows():
    formatted_data.append({
        "user": str(row[q_col]),
        "assistant": str(row[a_col])
    })

# Convert the cleaned Pandas DataFrame back to a Hugging Face Dataset object
clean_dataset = Dataset.from_list(formatted_data)

# Split into Training and Validation sets (90% Train, 10% Val)
final_dataset = clean_dataset.train_test_split(test_size=0.1)

print("Dataset successfully cleaned and split into:")
print(f"Training samples: {len(final_dataset['train'])}")
print(f"Validation samples: {len(final_dataset['test'])}")

# Define final save path
clean_drive_path = "/content/drive/MyDrive/Medical_QA_Project_Cleaned"

# Save the DatasetDict to disk
final_dataset.save_to_disk(clean_drive_path)

print(f"Cleaned dataset saved successfully at: {clean_drive_path}")

"""TEST BASE MODEL

"""

# Install required libraries for quantization and fine-tuning
!pip install -U bitsandbytes>=0.46.1 transformers accelerate peft trl datasets

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# Using the 0.5B model to show a clear difference after fine-tuning
model_id = "Qwen/Qwen2.5-0.5B-Instruct"

print("Loading the Small Base Model (0.5B)...")
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

print(f"Small model loaded. Memory footprint: {model.get_memory_footprint() / 1e6:.2f} MB")

def generate_response(model, tokenizer, question, max_new_tokens=150):
    prompt = f"User: {question}\nAssistant:"
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    full_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer = full_output.split("Assistant:")[-1].strip()
    return answer

# Use the same sample questions
sample_questions = [
    "ما هي أعراض الانفلونزا الموسمية؟",
    "كيف يتم علاج نقص الحديد في الجسم؟",
    "ما هي الإسعافات الأولية للحروق البسيطة؟"
]

print("--- SMALL BASE MODEL RESPONSES (0.5B - Pre-Training) ---")
for q in sample_questions:
    print(f"\nQuestion: {q}")
    # We use the same generate_response function defined earlier
    print(f"Base Answer: {generate_response(model, tokenizer, q)}")
    print("-" * 30)

# Install specific, stable versions to prevent library conflicts
!pip install huggingface_hub==0.25.2 transformers==4.46.1 peft accelerate trl datasets

print("Libraries installed successfully. You can now proceed.")
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# Using Qwen 0.5B to show clear improvement after training
model_id = "Qwen/Qwen2.5-0.5B-Instruct"

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

# Load Model in float16 (Full Precision)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

print(f"Model loaded successfully. VRAM used: {model.get_memory_footprint() / 1e6:.2f} MB")

from peft import LoraConfig, get_peft_model

# Define LoRA parameters for efficient fine-tuning
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

# Apply LoRA to the model
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

from datasets import load_from_disk
from google.colab import drive

# 1. Ensure Google Drive is mounted
drive.mount('/content/drive')

# 2. Load the cleaned dataset
clean_drive_path = "/content/drive/MyDrive/Medical_QA_Project_Cleaned"
print("Loading the cleaned dataset from Google Drive...")
final_dataset = load_from_disk(clean_drive_path)

# 3. Create a formatting function for Causal Language Modeling
def format_prompt(example):
    # Combine User and Assistant text, adding the EOS token
    combined_text = f"User: {example['user']}\nAssistant: {example['assistant']}{tokenizer.eos_token}"
    return {"text": combined_text}

# 4. Apply the formatting
print("Formatting dataset...")
formatted_dataset = final_dataset.map(format_prompt)

print("Dataset loaded and formatted successfully!")

import os
from trl import SFTTrainer, SFTConfig

# 1. Define Drive path for checkpoints
drive_checkpoints_path = "/content/drive/MyDrive/Medical_Qwen_Checkpoints"
os.makedirs(drive_checkpoints_path, exist_ok=True)

# 2. Define Training Arguments
training_args = SFTConfig(
    output_dir=drive_checkpoints_path, # Saves directly to Google Drive
    dataset_text_field="text",
    max_seq_length=512,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    optim="adamw_torch",
    learning_rate=2e-4,
    num_train_epochs=10,
    save_strategy="epoch", # Checkpoint saved strictly at the end of each epoch
    logging_steps=10,
    fp16=True,
    report_to="none"
)

# 3. Initialize the Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=formatted_dataset["train"],
    eval_dataset=formatted_dataset["test"],
    processing_class=tokenizer,
    args=training_args,
)

# 4. Start Fine-Tuning
print(f"Starting Standard LoRA Fine-Tuning for 10 Epochs...")
print(f"Checkpoints will be saved automatically to: {drive_checkpoints_path}")
trainer.train()

import matplotlib.pyplot as plt

# Extract logging history to visualize convergence
history = trainer.state.log_history
train_loss = [x['loss'] for x in history if 'loss' in x]
steps = [x['step'] for x in history if 'loss' in x]

plt.figure(figsize=(10, 5))
plt.plot(steps, train_loss, label='Training Loss', color='blue', linewidth=2)
plt.title('Training Loss Curve (Model Convergence)')
plt.xlabel('Step')
plt.ylabel('Loss')
plt.grid(True)
plt.legend()
plt.show()



